#java -Dspring.profiles.active=jack -jar december.jar
voice:
  add:
    - '{"name":"Jack","copy":"Nicolas"}'
    - '{"name":"Jack","copy":"Brian"}'
  default: Jack
repeat:
  stimulus: so
  response: |
    Then I went down to Los Angeles
    We'll ride horses like cowboys.
    Yeah.
    Sure, if you like.
    And chew tobacco like a man.
    What, they didn't teach you that in finishing school?
    Come on, I'll show you. Let's do it. I'll show you how, come on.
    Come on.
    Come on.
    Watch closely.
